name: Modules Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U pytest
      - run: echo "Testing"
      - name: Unit Testing
        uses: actions/checkout@v3
      - run: cd tests/
      - run: pytest

      - run: echo "Complete"
